[package]
name = "ssh-agent-lib"
description = "A collection of types for writing custom SSH agents"
version = "0.3.0-pre"
license = "MIT"
authors = [
    "Nicolas Trippar <ntrippar@gmail.com>",
    "Federico Pomar <fmpomar@users.noreply.github.com>",
    "Wiktor Kwapisiewicz <wiktor@metacode.biz>"
]
repository = "https://github.com/wiktor-k/ssh-agent.rs"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
serde = {version = "1", features = ["derive"]}

async-trait = { version = "0.1.77", optional = true }
bytes = { version = "1.5.0", optional = true }
futures = { version = "0.3.30", optional = true }
log = { version = "0.4.6", optional = true }
tokio = { version = "1", optional = true, features = ["rt", "net"] }
tokio-util = { version = "0.7.1", optional = true, features = ["codec"] }

[features]
default = ["agent"]
agent = ["futures", "log", "tokio", "tokio-util", "bytes", "async-trait"]

[[example]]
name = "key_storage"
required-features = ["agent"]

[dev-dependencies]
env_logger = "0.11.0"
openssl = "0.10.16"
tokio = { version = "1", features = ["macros"] }
