[package]
name = "ssh-agent-lib"
description = "A collection of types for writing custom SSH agents"
version = "0.2.6"
license = "MIT"
authors = [
    "Nicolas Trippar <ntrippar@gmail.com>",
    "Federico Pomar <fmpomar@users.noreply.github.com>",
    "Wiktor Kwapisiewicz <wiktor@metacode.biz>"
]
repository = "https://github.com/wiktor-k/ssh-agent.rs"
edition = "2021"

[dependencies]
byteorder = "1.2.7"
serde = {version = "1.0.87", features = ["derive"]}
service-binding = "^0.3.0"
bytes = { version = "0.4.11", optional = true }
futures = { version = "0.1.25", optional = true }
log = { version = "0.4.6", optional = true }
tokio = { version = "0.1.15", optional = true }
tokio-uds = { version = "0.2.5", optional = true }

[features]
default = ["agent"]
agent = ["futures", "log", "tokio", "tokio-uds", "bytes"]

[[example]]
name = "key_storage"
required-features = ["agent"]

[dev-dependencies]
env_logger = "0.6.0"
openssl = "0.10.16"
